channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=20.0.2
  - pytest  # dev
  - mypy  # dev
  - coverage  # dev
  - pip:
    - pynput
    - cursor==1.3.4
    - screeninfo==0.6.5
    - termcolor
    - types-termcolor  # dev
    - monostate
    - more_itertools
    - git+https://github.com/w2sv/Lingularity-_Backend.git
    - git+https://github.com/w2sv/asciiplot.git