name: frontend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0.2
  - pytest  # dev
  - mypy  # dev
  - pip:
     - git+https://W2SV@bitbucket.org/W2SV/backend.git@master
     - git+https://W2SV@bitbucket.org/W2SV/asciichartpy_extended.git@master
#    - ../backend/dist/backend-0.1.2-py3-none-any.whl
#    - ../backend/dist/asciichartpy_extended-0.0.1-py3-none-any.whl
    - coverage  # dev
    - pynput==1.6.8
    - cursor==1.3.4
    - screeninfo==0.6.5
    - termcolor
