channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0.2
  - pytest  # dev
  - mypy  # dev
  - coverage  # dev
  - pip:
    - pynput==1.6.8
    - cursor==1.3.4
    - screeninfo==0.6.5
    - termcolor
    - git+https://github.com/w2sv/Lingularity-Backend.git
    - git+https://github.com/w2sv/asciiplot.git